<a href="https://colab.research.google.com/github/jagadeeshdandu/NASSCOM-AI-FDP/blob/main/NASSCOM_Day_2_Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")

# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")

--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---


In [4]:
#Create a 1D array named 'arr1_1' with numbers from 0 to 99 (inclusive) using arange.
arr1_1 = np.arange(100)
print(arr1_1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [6]:
#Create a 3x3 array named 'arr1_2' filled with ones.
arr1_2 = np.ones((3, 3))
print(arr1_2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
#Create a 2x4 array named 'arr1_3' filled with the number 7.
arr1_3 = np.full((2, 4), 7)
print(arr1_3)

[[7 7 7 7]
 [7 7 7 7]]


In [12]:
# Create a 5x5 array named 'arr1_4' with random integers between 10 and 50 (inclusive).
arr1_4 = np.random.randint(10, 51, size=(5, 5))

print(arr1_4)

[[36 21 34 33 35]
 [28 46 46 22 46]
 [29 35 26 45 25]
 [21 15 41 47 28]
 [32 39 31 48 25]]


In [13]:
print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])

arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[36 21 34 33 35]
 [28 46 46 22 46]]


In [14]:
print("\n--- Task 2: Indexing and Slicing with Arrays ---")
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])



--- Task 2: Indexing and Slicing with Arrays ---


In [16]:
#Extract the element at row 2, column 3 (0-indexed). Store it in 'val2_1'.
val2_1 = data[2, 3]
print(val2_1)

120


In [17]:
# Extract the first row. Store it in 'row2_2'.
row2_2 = data[0, :]
print(row2_2)

[10 20 30 40]


In [18]:
# Extract the last column. Store it in 'col2_3'.
col2_3 = data[:, -1]
print(col2_3)

[ 40  80 120 160]


In [19]:
# Extract the sub-array consisting of rows 1 and 2, and columns 0 and 1. Store it in 'sub_arr2_4'.
sub_arr2_4 = data[1:3, 0:2]
print(sub_arr2_4)

[[ 50  60]
 [ 90 100]]


In [20]:
# Using boolean indexing, select all elements in 'data' that are greater than 100. Store them in 'filtered_elements2_5'.
filtered_elements2_5 = data[data > 100]
print(filtered_elements2_5)

[110 120 130 140 150 160]


In [21]:
# Task 3: Conditional Operations
print("\n--- Task 3: Conditional Operations ---")
arr3_1 = np.random.randint(1, 21, size=(4, 5)) # Random 4x5 array with values 1 to 20


--- Task 3: Conditional Operations ---


In [22]:
# Create a new array 'arr3_2' where elements in 'arr3_1' less than 10 are replaced with 0,
# and elements greater than or equal to 10 remain unchanged.
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)
print(arr3_2)

[[16 12  0  0  0]
 [ 0  0 13 19  0]
 [ 0 18 14  0 19]
 [12  0 18  0 17]]


In [23]:
# Count how many elements in 'arr3_1' are even. Store the count in 'even_count3_3'.
even_count3_3 = np.sum(arr3_1 % 2 == 0)
print(f"Number of even elements in arr3_1: {even_count3_3}")

Number of even elements in arr3_1: 11


In [24]:
# Task 4: Aggregation Functions
print("\n--- Task 4: Aggregation Functions ---")
arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])


--- Task 4: Aggregation Functions ---


In [25]:
# Calculate the sum of all elements in 'arr4_1'. Store it in 'sum4_1'.
sum4_1 = np.sum(arr4_1)
print(f"Sum of all elements in arr4_1: {sum4_1}")

Sum of all elements in arr4_1: 84


In [26]:
# Calculate the mean of each column. Store it in 'mean_cols4_2'.
mean_cols4_2 = np.mean(arr4_1, axis=0)
print(f"Mean of each column in arr4_1: {mean_cols4_2}")

Mean of each column in arr4_1: [11.          6.66666667 10.33333333]


In [27]:
# Find the maximum value in each row. Store it in 'max_rows4_3'.
max_rows4_3 = np.max(arr4_1, axis=1)
print(f"Maximum value in each row of arr4_1: {max_rows4_3}")

Maximum value in each row of arr4_1: [12 15 20]


In [28]:
# Calculate the standard deviation of the entire array. Store it in 'std4_4'.
std4_4 = np.std(arr4_1)
print(f"Standard deviation of arr4_1: {std4_4}")

Standard deviation of arr4_1: 5.2493385826745405


In [29]:
# Task 5: Reshaping and Flattening
print("\n--- Task 5: Reshaping and Flattening ---")
arr5_1 = np.arange(24) # 1D array from 0 to 23


--- Task 5: Reshaping and Flattening ---


In [31]:
# Reshape 'arr5_1' into a 4x6 2D array. Store it in 'reshaped_arr5_2'.
reshaped_arr5_2 = arr5_1.reshape((4, 6))
print("Reshaped arr5_2 (4x6):\n", reshaped_arr5_2)

Reshaped arr5_2 (4x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [32]:
# Reshape 'arr5_1' into a 2x3x4 3D array. Store it in 'reshaped_arr5_3'.
reshaped_arr5_3 = arr5_1.reshape((2, 3, 4))
print("Reshaped arr5_3 (2x3x4):\n", reshaped_arr5_3)

Reshaped arr5_3 (2x3x4):
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [33]:
# Flatten 'reshaped_arr5_2' back into a 1D array. Store it in 'flattened_arr5_4'.
# Use both `.ravel()` and `.flatten()` to see if there's a difference (though not visible in output).
flattened_arr5_4_ravel = reshaped_arr5_2.ravel()
flattened_arr5_4_flatten = reshaped_arr5_2.flatten()

print("Flattened arr5_4 (using .ravel()):\n", flattened_arr5_4_ravel)
print("Flattened arr5_4 (using .flatten()):\n", flattened_arr5_4_flatten)

Flattened arr5_4 (using .ravel()):
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Flattened arr5_4 (using .flatten()):
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [34]:
# Task 6: Broadcasting
print("\n--- Task 6: Broadcasting ---")
arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
scalar = 10
vector = np.array([100, 200, 300])


--- Task 6: Broadcasting ---


In [36]:
# Add the 'scalar' to every element of 'arr6_1'. Store it in 'result6_1'.
result6_1 = arr6_1 + scalar
print("arr6_1 + scalar:\n", result6_1)

arr6_1 + scalar:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]


In [37]:
# Add the 'vector' to each row of 'arr6_1'. Store it in 'result6_2'.
result6_2 = arr6_1 + vector
print("arr6_1 + vector (row-wise broadcasting):\n", result6_2)

arr6_1 + vector (row-wise broadcasting):
 [[101 202 303]
 [104 205 306]
 [107 208 309]]


In [38]:
# Task 7: Copying vs. Viewing Arrays
print("\n--- Task 7: Copying vs. Viewing Arrays ---")
original_arr7 = np.array([1, 2, 3, 4, 5])


--- Task 7: Copying vs. Viewing Arrays ---


In [39]:
# Create a 'view' of 'original_arr7' named 'view_arr7' by slicing the entire array.
view_arr7 = original_arr7[:]
print("Original array before modification:", original_arr7)
print("View array before modification:", view_arr7)

# Modify the first element of 'view_arr7' to 99.
view_arr7[0] = 99

# Observe how 'original_arr7' changes.
print("\nOriginal array after view modification:", original_arr7)
print("View array after modification:", view_arr7)

Original array before modification: [1 2 3 4 5]
View array before modification: [1 2 3 4 5]

Original array after view modification: [99  2  3  4  5]
View array after modification: [99  2  3  4  5]


In [40]:
# Create a 'copy' of 'original_arr7' named 'copy_arr7' using `.copy()`.
copy_arr7 = original_arr7.copy()
print("\nOriginal array before copy modification:", original_arr7)
print("Copy array before modification:", copy_arr7)

# Modify the last element of 'copy_arr7' to 0.
copy_arr7[-1] = 0

# Observe how 'original_arr7' remains unchanged.
print("\nOriginal array after copy modification:", original_arr7)
print("Copy array after modification:", copy_arr7)


Original array before copy modification: [99  2  3  4  5]
Copy array before modification: [99  2  3  4  5]

Original array after copy modification: [99  2  3  4  5]
Copy array after modification: [99  2  3  4  0]


In [41]:
# Task 8: Stacking and Splitting Arrays
print("\n--- Task 8: Stacking and Splitting Arrays ---")
arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])


--- Task 8: Stacking and Splitting Arrays ---


In [42]:
# Vertically stack 'arr8_a' and 'arr8_b'. Store it in 'vstack_arr8_1'.
vstack_arr8_1 = np.vstack((arr8_a, arr8_b))
print("Vertically stacked arr8_a and arr8_b:\n", vstack_arr8_1)

Vertically stacked arr8_a and arr8_b:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [43]:
# Horizontally stack 'arr8_a' and 'arr8_b'. Store it in 'hstack_arr8_2'.
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))
print("Horizontally stacked arr8_a and arr8_b:\n", hstack_arr8_2)

Horizontally stacked arr8_a and arr8_b:
 [[1 2 5 6]
 [3 4 7 8]]


In [44]:
# Vertically stack 'vstack_arr8_1' and 'arr8_c'. Store it in 'combined_arr8_3'.
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))
print("Vertically stacked vstack_arr8_1 and arr8_c:\n", combined_arr8_3)

Vertically stacked vstack_arr8_1 and arr8_c:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [46]:
# Split 'combined_arr8_3' into 3 parts (rows). Store them in 'part1', 'part2', 'part3'.
# Note: Since the number of rows (5) is not evenly divisible by 3, the parts will not be of equal size.
parts = np.array_split(combined_arr8_3, 3)
part1 = parts[0]
part2 = parts[1]
part3 = parts[2]

print("Part 1:\n", part1)
print("Part 2:\n", part2)
print("Part 3:\n", part3)

Part 1:
 [[1 2]
 [3 4]]
Part 2:
 [[5 6]
 [7 8]]
Part 3:
 [[ 9 10]]


In [47]:
# Task 9: Sorting and Searching
print("\n--- Task 9: Sorting and Searching ---")
arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])



--- Task 9: Sorting and Searching ---


In [48]:
# Sort 'arr9_1' in ascending order. Store it in 'sorted_arr9_1'.
sorted_arr9_1 = np.sort(arr9_1)
print("Sorted arr9_1:", sorted_arr9_1)

Sorted arr9_1: [1 2 3 4 5 6 7 8 9]


In [50]:
# Sort 'arr9_2d' along columns (i.e., each column sorted independently). Store it in 'sorted_cols9_2'.
sorted_arr9_2d_cols = np.sort(arr9_2d, axis=0)
print("Sorted arr9_2d along columns:\n", sorted_arr9_2d_cols)

Sorted arr9_2d along columns:
 [[30 20 10]
 [60 50 40]
 [90 80 70]]


In [52]:
# Find the indices where the value 9 is present in 'arr9_1'. Store it in 'idx9_3'. (Hint: use np.where)
idx9_3 = np.where(arr9_1 == 9)
print("Indices where 9 is present in arr9_1:", idx9_3)

Indices where 9 is present in arr9_1: (array([4]),)


In [54]:
# Find the index of the maximum value in 'arr9_1'. Store it in 'max_idx9_4'.
max_idx9_4 = np.argmax(arr9_1)
print("Index of the maximum value in arr9_1:", max_idx9_4)

Index of the maximum value in arr9_1: 4
